(()=>{'use strict';const F=window.FORGE,$=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)];
F.loadSave();F.applyOfflineProgress();F.applyTheme();F.updateAchievements();F.persist();
function boot(){const fill=$('bootFill'),text=$('bootText'),app=$('app');if(F.save.settings.reducedMotion){$('boot').classList.remove('active');app.setAttribute('aria-hidden','false');F.ui.render();return}let p=0;const stages=[[18,'LOADING DAILY ENGINE…'],[38,'SYNCING BOARD…'],[62,'HEATING CORE…'],[82,'ROTATING LIVE EVENT…'],[100,'FORGE ONLINE']];const int=setInterval(()=>{p=Math.min(100,p+Math.random()*10+4);fill.style.width=`${p}%`;for(const [n,t] of stages)if(p>=n)text.textContent=t;if(p>=100){clearInterval(int);setTimeout(()=>{$('boot').classList.remove('active');app.setAttribute('aria-hidden','false');F.ui.render();F.ui.flushUnlocks()},220)}},80)}
function bind(){$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>F.ui.nav(b.dataset.nav)));$('menuToggle').onclick=()=>$('sidebar').classList.toggle('open');$('dismissAway').onclick=()=>{$('awayCard').classList.add('hidden');F.away.mins=0};$('questModalClose').onclick=()=>F.ui.closeQuest();$('questModal').addEventListener('click',e=>{if(e.target===$('questModal'))F.ui.closeQuest()});$('clipModalClose').onclick=()=>F.ui.closeClip();$('clipModal').addEventListener('click',e=>{if(e.target===$('clipModal'))F.ui.closeClip()});$('clipSearch').addEventListener('input',()=>F.ui.current==='clips'&&F.ui.clips());$('clipFilter').addEventListener('change',()=>F.ui.current==='clips'&&F.ui.clips());$('reducedMotion').onchange=e=>{F.save.settings.reducedMotion=e.target.checked;F.persist();F.ui.meta()};$$('[data-mix]').forEach(b=>b.onclick=()=>{F.save.settings.mix=b.dataset.mix;F.persist();F.ui.settings();F.ui.toast('DAILY MIX UPDATED','Tomorrow’s split will use this preference.',true)});$('exportBtn').onclick=()=>F.exportSave();$('importBtn').onclick=()=>$('importInput').click();$('importInput').onchange=async e=>{try{await F.importSave(e.target.files[0]);location.reload()}catch{F.ui.toast('IMPORT FAILED','That save file could not be read.')}};$('resetProgressBtn').onclick=()=>{if(confirm('Reset all Forge progression? Proof clips are not erased by this button.')){localStorage.removeItem(F.SAVE_KEY);location.reload()}};$('clearClipsBtn').onclick=async()=>{if(confirm('Erase every stored proof clip on this device?')){await F.clearClips();F.save.stats.clips=0;F.persist();F.ui.toast('CLIPS CLEARED','Local proof archive erased.',true);F.ui.render()}};addEventListener('keydown',e=>{if(e.key==='Escape'){F.ui.closeQuest();F.ui.closeClip();$('sidebar').classList.remove('open')}})}
function clocks(){const e=F.currentEvent();$('eventTimer').textContent=F.formatClock((e.end-Date.now())/1000);$('resetTimer').textContent=F.formatClock(F.secondsToMidnight());const heat=Math.floor(F.save.coreHeat);$('heatBig').textContent=heat;$('miniHeat').textContent=heat}
let last=performance.now();function heartbeat(t){const dt=Math.min(5,(t-last)/1000);last=t;F.tickCore(dt);clocks();requestAnimationFrame(heartbeat)}
function ambient(){const c=$('ambientCanvas'),ctx=c.getContext('2d');let w=0,h=0,dpr=1,pts=[];const resize=()=>{dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);pts=Array.from({length:Math.min(80,Math.floor(w*h/22000))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.4+.25,vx:(Math.random()-.5)*3,vy:-Math.random()*9-2,a:Math.random()*.25+.05}))};resize();addEventListener('resize',resize);function draw(){ctx.clearRect(0,0,w,h);if(!F.save.settings.reducedMotion){for(const p of pts){p.x+=p.vx*.016;p.y+=p.vy*.016;if(p.y<-10){p.y=h+10;p.x=Math.random()*w}ctx.fillStyle=`rgba(255,115,55,${p.a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}}requestAnimationFrame(draw)}draw()}
bind();ambient();boot();requestAnimationFrame(heartbeat);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});addEventListener('beforeunload',()=>F.persist());
})();
