(()=>{'use strict';const F=window.FORGE,$=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
F.ui={current:'home',proofFile:null,proofUrl:null,
 toast(title,text='',good=false){const d=document.createElement('div');d.className=`toast${good?' good':''}`;d.innerHTML=`<b>${esc(title)}</b>${text?`<p>${esc(text)}</p>`:''}`;$('toastStack').appendChild(d);setTimeout(()=>{d.style.opacity='0';d.style.transform='translateX(20px)';setTimeout(()=>d.remove(),250)},3200)},
 nav(page){this.current=page;$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.classList.contains('nav-item')&&b.dataset.nav===page));$('sidebar').classList.remove('open');this.render();scrollTo({top:0,behavior:F.save.settings.reducedMotion?'auto':'smooth'})},
 render(){this.meta();if(this.current==='home')this.home();if(this.current==='board')this.board();if(this.current==='clips')this.clips();if(this.current==='progress')this.progress();if(this.current==='vault')this.vault();if(this.current==='settings')this.settings()},
 meta(){const l=F.levelFromXp(F.save.xp),b=F.board(),done=b.quests.filter(F.isComplete).length;$('levelTop').textContent=l.level;$('sparksTop').textContent=Math.floor(F.save.sparks);$('boardBadge').textContent=5-done;$('miniHeat').textContent=Math.floor(F.save.coreHeat);$('miniHeatState').textContent=F.save.coreHeat>=80?'WHITE HOT':F.save.coreHeat>=50?'BURNING':F.save.coreHeat>=20?'WARM':'COLD';$('heatBig').textContent=Math.floor(F.save.coreHeat);document.body.classList.toggle('reduced-motion',!!F.save.settings.reducedMotion)},
 home(){const b=F.board(),done=b.quests.filter(F.isComplete).length,e=F.currentEvent(),away=F.away||{};$('completionFraction').textContent=`${done}/5`;$('dailyProgressBar').style.width=`${done*20}%`;$('dailyProgressText').textContent=done===5?'Board complete. Forge streak secured.':`${5-done} quest${5-done===1?'':'s'} remain.`;$('homeQuestStrip').innerHTML=b.quests.map(q=>`<div class="quest-pip ${F.isComplete(q)?'complete':''}"><b>${F.isComplete(q)?'✓':F.GAMES[q.game].icon}</b><small>${F.GAMES[q.game].name}</small></div>`).join('');$('streakStat').textContent=F.save.streak;$('sparksStat').textContent=Math.floor(F.save.sparks);$('vrfsMasteryStat').textContent=Math.floor(F.save.mastery.vrfs);$('valMasteryStat').textContent=Math.floor(F.save.mastery.valorant);$('eventCard').innerHTML=`<div class="event-icon">${e.icon}</div><h3>${esc(e.name)}</h3><p>${esc(e.desc)}</p><span class="event-bonus">${esc(e.label)}</span>`;$('bossPreview').innerHTML=this.bossMarkup(b.boss,true);
   if(away.mins>5){$('awayCard').classList.remove('hidden');const parts=[];if(away.boardChanged)parts.push('a new daily board rolled');if(away.eventChanges)parts.push(`${away.eventChanges} live rotation${away.eventChanges===1?'':'s'} passed`);if(away.heatGain>.5)parts.push(`Core Heat rose ${Math.floor(away.heatGain)}%`);$('awayText').textContent=parts.length?parts.join(' • '):'Core Heat kept building while Forge was closed.';$('awayTitle').textContent=away.boardChanged?'A fresh board is live.':'The Forge kept moving.'}else $('awayCard').classList.add('hidden')},
 questMarkup(q){const g=F.GAMES[q.game],d=F.DIFFICULTIES[q.difficulty],done=F.isComplete(q);return `<article class="quest-card ${done?'complete':''}" style="--questColor:${g.color};animation-delay:${q.index*.055}s"><div class="quest-game"><span class="game-badge">${g.name}</span><span class="difficulty">${d.name}</span></div><div class="quest-symbol">${esc(q.symbol)}</div><h3>${esc(q.name)}</h3><p>${esc(q.desc)}</p><div class="quest-reward-row"><span class="reward-pill">+${q.xp} XP</span><span class="reward-pill">+${q.sparks} ✦</span></div><button class="btn ${done?'ghost':'primary'}" data-quest="${q.id}">${done?'VIEW PROOF':'COMPLETE + PROOF'}</button></article>`},
 bossMarkup(q,preview=false){const g=F.GAMES[q.game],done=F.isBossComplete(q);return `<div class="boss-content"><div class="boss-icon">♛</div><div><small>${g.name} // BOSS QUEST</small><h3>${esc(q.name)}</h3><p>${esc(q.desc)}</p></div><div class="reward-column"><b>+${q.xp} XP</b><small>+${q.sparks} SPARKS</small>${preview?'':`<button class="btn ${done?'ghost':'primary'}" data-boss="${q.id}">${done?'VIEW PROOF':'TAKE BOSS'}</button>`}</div></div>`},
 board(){const b=F.board(),done=b.quests.filter(F.isComplete).length;$('boardDate').textContent=F.prettyDay(b.key);$('boardComplete').textContent=`${done}/5`;$('questGrid').innerHTML=b.quests.map(q=>this.questMarkup(q)).join('');$('bossQuest').innerHTML=this.bossMarkup(b.boss);this.bindQuestButtons()},
 bindQuestButtons(){$$('[data-quest]').forEach(b=>b.onclick=()=>{const q=F.board().quests.find(x=>x.id===b.dataset.quest);this.openQuest(q,false)});$$('[data-boss]').forEach(b=>b.onclick=()=>this.openQuest(F.board().boss,true))},
 async openQuest(q,isBoss){const done=isBoss?F.isBossComplete(q):F.isComplete(q),rec=done?(isBoss?F.save.bossCompleted[q.id]:F.save.completed[q.id]):null,g=F.GAMES[q.game];this.proofFile=null;if(this.proofUrl){URL.revokeObjectURL(this.proofUrl);this.proofUrl=null}$('questModalBody').innerHTML=`<div class="modal-game">${g.name} // ${isBoss?'BOSS QUEST':'DAILY QUEST'}</div><h2>${esc(q.name)}</h2><p>${esc(q.desc)}</p><div class="modal-rewards"><span class="reward-pill">BASE +${q.xp} XP</span><span class="reward-pill">+${q.sparks} ✦</span><span class="reward-pill">HEAT ${Math.floor(F.save.coreHeat)}%</span></div>${done?`<div id="existingProof" class="proof-zone"><div class="proof-icon">✓</div><h3>Quest completed</h3><p>Loading saved proof…</p></div>`:`<div id="proofZone" class="proof-zone"><div class="proof-icon">⇧</div><h3>Attach your proof</h3><p>Video clip or screenshot. No manual stat entry.</p><button id="chooseProof" class="btn ghost">CHOOSE FILE</button><input id="proofInput" type="file" accept="video/*,image/*"><div id="proofPreview"></div></div><div class="complete-actions"><button id="completeQuestBtn" class="btn primary">VERIFY & COMPLETE</button></div>`}`;$('questModal').classList.remove('hidden');if(done){const clip=await F.getClip(rec.clipId);if(clip)this.renderProof('existingProof',clip.blob,clip.name)}else this.bindProof(q,isBoss)},
 bindProof(q,isBoss){const input=$('proofInput'),choose=$('chooseProof'),zone=$('proofZone');choose.onclick=()=>input.click();input.onchange=()=>this.setProof(input.files[0]);['dragenter','dragover'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>this.setProof(e.dataTransfer.files[0]));$('completeQuestBtn').onclick=async()=>{try{const reward=await F.completeQuest(q,this.proofFile,isBoss);this.closeQuest();this.toast('QUEST FORGED',`+${reward.xp} XP • +${reward.sparks} Sparks`,true);this.render();this.flushUnlocks()}catch(e){this.toast('PROOF REQUIRED',e.message)}}},
 setProof(file){if(!file)return;if(!(file.type.startsWith('video/')||file.type.startsWith('image/'))){this.toast('Unsupported file','Use a video clip or image.');return}this.proofFile=file;this.renderProof('proofPreview',file,file.name)},
 renderProof(id,blob,name){const el=$(id);if(!el)return;if(this.proofUrl)URL.revokeObjectURL(this.proofUrl);this.proofUrl=URL.createObjectURL(blob);const media=blob.type.startsWith('video/')?`<video controls playsinline src="${this.proofUrl}"></video>`:`<img src="${this.proofUrl}" alt="Quest proof">`;el.innerHTML=`<div class="proof-preview">${media}<div class="proof-file-name">${esc(name||'proof')}</div></div>`},
 closeQuest(){if(this.proofUrl){URL.revokeObjectURL(this.proofUrl);this.proofUrl=null}$('questModal').classList.add('hidden')},
 async clips(){const clips=await F.getClips(),q=($('clipSearch').value||'').toLowerCase(),f=$('clipFilter').value;const show=clips.filter(c=>(f==='all'||c.game===f)&&(!q||c.questName.toLowerCase().includes(q)||c.name.toLowerCase().includes(q)));$('emptyClips').classList.toggle('hidden',show.length>0);$('clipGrid').innerHTML=show.map(c=>`<article class="clip-card" data-clipid="${c.id}"><div class="clip-thumb"><div class="play">${c.type.startsWith('image/')?'▧':'▶'}</div><span class="clip-type">${c.type.startsWith('image/')?'IMAGE':'VIDEO'}</span></div><div class="clip-info"><small>${F.GAMES[c.game].name}</small><h3>${esc(c.questName)}</h3><p>${new Date(c.createdAt).toLocaleString()}</p></div></article>`).join('');$$('[data-clipid]').forEach(el=>el.onclick=()=>this.openClip(el.dataset.clipid))},
 async openClip(id){const c=await F.getClip(id);if(!c)return;const url=URL.createObjectURL(c.blob);$('clipModalBody').innerHTML=`<div class="modal-game">${F.GAMES[c.game].name} // PROOF</div><h2>${esc(c.questName)}</h2>${c.type.startsWith('video/')?`<video controls autoplay playsinline src="${url}"></video>`:`<img src="${url}" alt="Proof">`}<p>${esc(c.name)} • ${new Date(c.createdAt).toLocaleString()}</p>`;$('clipModal').dataset.url=url;$('clipModal').classList.remove('hidden')},
 closeClip(){const url=$('clipModal').dataset.url;if(url)URL.revokeObjectURL(url);$('clipModal').classList.add('hidden')},
 progress(){const l=F.levelFromXp(F.save.xp);$('levelBig').textContent=l.level;$('rankName').textContent=l.rank;$('xpLine').textContent=`${Math.floor(l.current)} / ${l.need} XP`;$('xpBar').style.width=`${l.progress*100}%`;$('nextUnlockText').textContent=`Level ${l.level+1} is ${Math.max(0,l.need-l.current)} XP away.`;$('vrfsMastery').textContent=Math.floor(F.save.mastery.vrfs);$('valMastery').textContent=Math.floor(F.save.mastery.valorant);$('vrfsMasteryLevel').textContent=F.masteryName(F.save.mastery.vrfs);$('valMasteryLevel').textContent=F.masteryName(F.save.mastery.valorant);const unlocked=F.ACHIEVEMENTS.filter(a=>F.save.achievements[a.id]).length;$('achievementCount').textContent=`${unlocked}/${F.ACHIEVEMENTS.length}`;$('achievementGrid').innerHTML=F.ACHIEVEMENTS.map(a=>`<div class="achievement ${F.save.achievements[a.id]?'unlocked':''}"><div class="ach-icon">${a.icon}</div><div><b>${esc(a.name)}</b><small>${esc(a.desc)}</small></div></div>`).join('');$('historyList').innerHTML=F.save.history.length?F.save.history.map(h=>`<div class="history-row"><small>${F.prettyDay(h.key)}</small><div class="history-pips">${Array.from({length:5},(_,i)=>`<i class="${i<h.done?'done':''}"></i>`).join('')}</div><b>${h.done}/5</b></div>`).join(''):`<p class="muted">Complete your first full daily board to start the archive.</p>`},
 vault(){const titles=F.availableTitles(),themes=F.availableThemes();$('activeTitle').textContent=(F.TITLES.find(t=>t.id===F.save.activeTitle)||F.TITLES[0]).name;$('activeTheme').textContent=(F.THEMES.find(t=>t.id===F.save.activeTheme)||F.THEMES[0]).name;$('titleGrid').innerHTML=titles.map(t=>`<div class="vault-item ${t.unlocked?'':'locked'}"><small>${t.unlocked?'UNLOCKED':esc(t.req)}</small><h3>${esc(t.name)}</h3><p>${t.id===F.save.activeTitle?'Currently equipped.':'Forge identity title.'}</p>${t.unlocked&&t.id!==F.save.activeTitle?`<button data-title="${t.id}">EQUIP</button>`:''}</div>`).join('');$('themeGrid').innerHTML=themes.map(t=>`<div class="vault-item ${t.unlocked?'':'locked'}"><div class="theme-swatch" style="--sw1:${t.sw1};--sw2:${t.sw2}"></div><small>${t.unlocked?'UNLOCKED':esc(t.req)}</small><h3>${esc(t.name)}</h3>${t.unlocked&&t.id!==F.save.activeTheme?`<button data-theme="${t.id}">EQUIP</button>`:''}</div>`).join('');$$('[data-title]').forEach(b=>b.onclick=()=>{F.setTitle(b.dataset.title);this.vault();this.toast('TITLE EQUIPPED','Forge identity updated.',true)});$$('[data-theme]').forEach(b=>b.onclick=()=>{F.setTheme(b.dataset.theme);this.vault();this.toast('SKIN EQUIPPED','Interface core recolored.',true)})},
 settings(){$('reducedMotion').checked=F.save.settings.reducedMotion;$$('[data-mix]').forEach(b=>b.classList.toggle('active',b.dataset.mix===F.save.settings.mix))},
 flushUnlocks(){for(const a of F.pendingUnlocks||[])this.toast(`ACHIEVEMENT: ${a.name}`,'+10 Sparks',true);F.pendingUnlocks=[]}
};})();
