window.FORGE_REWARDS = [
  {
    level: 1,
    kind: "title",
    name: "Rookie",
    value: "Rookie",
    description: "Unlocked automatically at account level 1.",
  },
  {
    level: 2,
    kind: "accent",
    name: "Violet Core",
    value: "#875cff",
    description: "Unlocked automatically at account level 2.",
  },
  {
    level: 3,
    kind: "frame",
    name: "Forge Frame 03",
    value: "frame-4",
    description: "Unlocked automatically at account level 3.",
  },
  {
    level: 4,
    kind: "badge",
    name: "Level 04 Mark",
    value: "mark-04",
    description: "Unlocked automatically at account level 4.",
  },
  {
    level: 5,
    kind: "title",
    name: "Clipper",
    value: "Clipper",
    description: "Unlocked automatically at account level 5.",
  },
  {
    level: 6,
    kind: "accent",
    name: "Neon Ice",
    value: "#59d6ff",
    description: "Unlocked automatically at account level 6.",
  },
  {
    level: 7,
    kind: "frame",
    name: "Forge Frame 07",
    value: "frame-8",
    description: "Unlocked automatically at account level 7.",
  },
  {
    level: 8,
    kind: "badge",
    name: "Level 08 Mark",
    value: "mark-08",
    description: "Unlocked automatically at account level 8.",
  },
  {
    level: 9,
    kind: "title",
    name: "Hunter",
    value: "Hunter",
    description: "Unlocked automatically at account level 9.",
  },
  {
    level: 10,
    kind: "accent",
    name: "Crimson Pulse",
    value: "#ff6576",
    description: "Unlocked automatically at account level 10.",
  },
  {
    level: 11,
    kind: "frame",
    name: "Forge Frame 11",
    value: "frame-4",
    description: "Unlocked automatically at account level 11.",
  },
  {
    level: 12,
    kind: "badge",
    name: "Level 12 Mark",
    value: "mark-12",
    description: "Unlocked automatically at account level 12.",
  },
  {
    level: 13,
    kind: "title",
    name: "Proof Collector",
    value: "Proof Collector",
    description: "Unlocked automatically at account level 13.",
  },
  {
    level: 14,
    kind: "accent",
    name: "Emerald Shift",
    value: "#52e3a4",
    description: "Unlocked automatically at account level 14.",
  },
  {
    level: 15,
    kind: "frame",
    name: "Forge Frame 15",
    value: "frame-8",
    description: "Unlocked automatically at account level 15.",
  },
  {
    level: 16,
    kind: "badge",
    name: "Level 16 Mark",
    value: "mark-16",
    description: "Unlocked automatically at account level 16.",
  },
  {
    level: 17,
    kind: "title",
    name: "Locked In",
    value: "Locked In",
    description: "Unlocked automatically at account level 17.",
  },
  {
    level: 18,
    kind: "accent",
    name: "Solar Gold",
    value: "#ffc85c",
    description: "Unlocked automatically at account level 18.",
  },
  {
    level: 19,
    kind: "frame",
    name: "Forge Frame 19",
    value: "frame-4",
    description: "Unlocked automatically at account level 19.",
  },
  {
    level: 20,
    kind: "badge",
    name: "Level 20 Mark",
    value: "mark-20",
    description: "Unlocked automatically at account level 20.",
  },
  {
    level: 21,
    kind: "title",
    name: "Quest Runner",
    value: "Quest Runner",
    description: "Unlocked automatically at account level 21.",
  },
  {
    level: 22,
    kind: "accent",
    name: "Electric Blue",
    value: "#3f8cff",
    description: "Unlocked automatically at account level 22.",
  },
  {
    level: 23,
    kind: "frame",
    name: "Forge Frame 23",
    value: "frame-8",
    description: "Unlocked automatically at account level 23.",
  },
  {
    level: 24,
    kind: "badge",
    name: "Level 24 Mark",
    value: "mark-24",
    description: "Unlocked automatically at account level 24.",
  },
  {
    level: 25,
    kind: "title",
    name: "Daily Grinder",
    value: "Daily Grinder",
    description: "Unlocked automatically at account level 25.",
  },
  {
    level: 26,
    kind: "accent",
    name: "Rose Circuit",
    value: "#ff77c8",
    description: "Unlocked automatically at account level 26.",
  },
  {
    level: 27,
    kind: "frame",
    name: "Forge Frame 27",
    value: "frame-4",
    description: "Unlocked automatically at account level 27.",
  },
  {
    level: 28,
    kind: "badge",
    name: "Level 28 Mark",
    value: "mark-28",
    description: "Unlocked automatically at account level 28.",
  },
  {
    level: 29,
    kind: "title",
    name: "Moment Maker",
    value: "Moment Maker",
    description: "Unlocked automatically at account level 29.",
  },
  {
    level: 30,
    kind: "accent",
    name: "Arctic White",
    value: "#e9eef8",
    description: "Unlocked automatically at account level 30.",
  },
  {
    level: 31,
    kind: "frame",
    name: "Forge Frame 31",
    value: "frame-8",
    description: "Unlocked automatically at account level 31.",
  },
  {
    level: 32,
    kind: "badge",
    name: "Level 32 Mark",
    value: "mark-32",
    description: "Unlocked automatically at account level 32.",
  },
  {
    level: 33,
    kind: "title",
    name: "Highlight Reel",
    value: "Highlight Reel",
    description: "Unlocked automatically at account level 33.",
  },
  {
    level: 34,
    kind: "accent",
    name: "Violet Core",
    value: "#875cff",
    description: "Unlocked automatically at account level 34.",
  },
  {
    level: 35,
    kind: "frame",
    name: "Forge Frame 35",
    value: "frame-4",
    description: "Unlocked automatically at account level 35.",
  },
  {
    level: 36,
    kind: "badge",
    name: "Level 36 Mark",
    value: "mark-36",
    description: "Unlocked automatically at account level 36.",
  },
  {
    level: 37,
    kind: "title",
    name: "Challenger",
    value: "Challenger",
    description: "Unlocked automatically at account level 37.",
  },
  {
    level: 38,
    kind: "accent",
    name: "Neon Ice",
    value: "#59d6ff",
    description: "Unlocked automatically at account level 38.",
  },
  {
    level: 39,
    kind: "frame",
    name: "Forge Frame 39",
    value: "frame-8",
    description: "Unlocked automatically at account level 39.",
  },
  {
    level: 40,
    kind: "badge",
    name: "Level 40 Mark",
    value: "mark-40",
    description: "Unlocked automatically at account level 40.",
  },
  {
    level: 41,
    kind: "title",
    name: "On A Run",
    value: "On A Run",
    description: "Unlocked automatically at account level 41.",
  },
  {
    level: 42,
    kind: "accent",
    name: "Crimson Pulse",
    value: "#ff6576",
    description: "Unlocked automatically at account level 42.",
  },
  {
    level: 43,
    kind: "frame",
    name: "Forge Frame 43",
    value: "frame-4",
    description: "Unlocked automatically at account level 43.",
  },
  {
    level: 44,
    kind: "badge",
    name: "Level 44 Mark",
    value: "mark-44",
    description: "Unlocked automatically at account level 44.",
  },
  {
    level: 45,
    kind: "title",
    name: "Mission Hunter",
    value: "Mission Hunter",
    description: "Unlocked automatically at account level 45.",
  },
  {
    level: 46,
    kind: "accent",
    name: "Emerald Shift",
    value: "#52e3a4",
    description: "Unlocked automatically at account level 46.",
  },
  {
    level: 47,
    kind: "frame",
    name: "Forge Frame 47",
    value: "frame-8",
    description: "Unlocked automatically at account level 47.",
  },
  {
    level: 48,
    kind: "badge",
    name: "Level 48 Mark",
    value: "mark-48",
    description: "Unlocked automatically at account level 48.",
  },
  {
    level: 49,
    kind: "title",
    name: "Clutch Archive",
    value: "Clutch Archive",
    description: "Unlocked automatically at account level 49.",
  },
  {
    level: 50,
    kind: "accent",
    name: "Solar Gold",
    value: "#ffc85c",
    description: "Unlocked automatically at account level 50.",
  },
  {
    level: 51,
    kind: "frame",
    name: "Forge Frame 51",
    value: "frame-4",
    description: "Unlocked automatically at account level 51.",
  },
  {
    level: 52,
    kind: "badge",
    name: "Level 52 Mark",
    value: "mark-52",
    description: "Unlocked automatically at account level 52.",
  },
  {
    level: 53,
    kind: "title",
    name: "Pitch Archive",
    value: "Pitch Archive",
    description: "Unlocked automatically at account level 53.",
  },
  {
    level: 54,
    kind: "accent",
    name: "Electric Blue",
    value: "#3f8cff",
    description: "Unlocked automatically at account level 54.",
  },
  {
    level: 55,
    kind: "frame",
    name: "Forge Frame 55",
    value: "frame-8",
    description: "Unlocked automatically at account level 55.",
  },
  {
    level: 56,
    kind: "badge",
    name: "Level 56 Mark",
    value: "mark-56",
    description: "Unlocked automatically at account level 56.",
  },
  {
    level: 57,
    kind: "title",
    name: "Forged",
    value: "Forged",
    description: "Unlocked automatically at account level 57.",
  },
  {
    level: 58,
    kind: "accent",
    name: "Rose Circuit",
    value: "#ff77c8",
    description: "Unlocked automatically at account level 58.",
  },
  {
    level: 59,
    kind: "frame",
    name: "Forge Frame 59",
    value: "frame-4",
    description: "Unlocked automatically at account level 59.",
  },
  {
    level: 60,
    kind: "badge",
    name: "Level 60 Mark",
    value: "mark-60",
    description: "Unlocked automatically at account level 60.",
  },
  {
    level: 61,
    kind: "title",
    name: "Overdrive",
    value: "Overdrive",
    description: "Unlocked automatically at account level 61.",
  },
  {
    level: 62,
    kind: "accent",
    name: "Arctic White",
    value: "#e9eef8",
    description: "Unlocked automatically at account level 62.",
  },
  {
    level: 63,
    kind: "frame",
    name: "Forge Frame 63",
    value: "frame-8",
    description: "Unlocked automatically at account level 63.",
  },
  {
    level: 64,
    kind: "badge",
    name: "Level 64 Mark",
    value: "mark-64",
    description: "Unlocked automatically at account level 64.",
  },
  {
    level: 65,
    kind: "title",
    name: "No Days Wasted",
    value: "No Days Wasted",
    description: "Unlocked automatically at account level 65.",
  },
  {
    level: 66,
    kind: "accent",
    name: "Violet Core",
    value: "#875cff",
    description: "Unlocked automatically at account level 66.",
  },
  {
    level: 67,
    kind: "frame",
    name: "Forge Frame 67",
    value: "frame-4",
    description: "Unlocked automatically at account level 67.",
  },
  {
    level: 68,
    kind: "badge",
    name: "Level 68 Mark",
    value: "mark-68",
    description: "Unlocked automatically at account level 68.",
  },
  {
    level: 69,
    kind: "title",
    name: "Perfect Five",
    value: "Perfect Five",
    description: "Unlocked automatically at account level 69.",
  },
  {
    level: 70,
    kind: "accent",
    name: "Neon Ice",
    value: "#59d6ff",
    description: "Unlocked automatically at account level 70.",
  },
  {
    level: 71,
    kind: "frame",
    name: "Forge Frame 71",
    value: "frame-8",
    description: "Unlocked automatically at account level 71.",
  },
  {
    level: 72,
    kind: "badge",
    name: "Level 72 Mark",
    value: "mark-72",
    description: "Unlocked automatically at account level 72.",
  },
  {
    level: 73,
    kind: "title",
    name: "Clip Machine",
    value: "Clip Machine",
    description: "Unlocked automatically at account level 73.",
  },
  {
    level: 74,
    kind: "accent",
    name: "Crimson Pulse",
    value: "#ff6576",
    description: "Unlocked automatically at account level 74.",
  },
  {
    level: 75,
    kind: "frame",
    name: "Forge Frame 75",
    value: "frame-4",
    description: "Unlocked automatically at account level 75.",
  },
  {
    level: 76,
    kind: "badge",
    name: "Level 76 Mark",
    value: "mark-76",
    description: "Unlocked automatically at account level 76.",
  },
  {
    level: 77,
    kind: "title",
    name: "Quest Engine",
    value: "Quest Engine",
    description: "Unlocked automatically at account level 77.",
  },
  {
    level: 78,
    kind: "accent",
    name: "Emerald Shift",
    value: "#52e3a4",
    description: "Unlocked automatically at account level 78.",
  },
  {
    level: 79,
    kind: "frame",
    name: "Forge Frame 79",
    value: "frame-8",
    description: "Unlocked automatically at account level 79.",
  },
  {
    level: 80,
    kind: "badge",
    name: "Level 80 Mark",
    value: "mark-80",
    description: "Unlocked automatically at account level 80.",
  },
  {
    level: 81,
    kind: "title",
    name: "Streak Keeper",
    value: "Streak Keeper",
    description: "Unlocked automatically at account level 81.",
  },
  {
    level: 82,
    kind: "accent",
    name: "Solar Gold",
    value: "#ffc85c",
    description: "Unlocked automatically at account level 82.",
  },
  {
    level: 83,
    kind: "frame",
    name: "Forge Frame 83",
    value: "frame-4",
    description: "Unlocked automatically at account level 83.",
  },
  {
    level: 84,
    kind: "badge",
    name: "Level 84 Mark",
    value: "mark-84",
    description: "Unlocked automatically at account level 84.",
  },
  {
    level: 85,
    kind: "title",
    name: "Proof Runner",
    value: "Proof Runner",
    description: "Unlocked automatically at account level 85.",
  },
  {
    level: 86,
    kind: "accent",
    name: "Electric Blue",
    value: "#3f8cff",
    description: "Unlocked automatically at account level 86.",
  },
  {
    level: 87,
    kind: "frame",
    name: "Forge Frame 87",
    value: "frame-8",
    description: "Unlocked automatically at account level 87.",
  },
  {
    level: 88,
    kind: "badge",
    name: "Level 88 Mark",
    value: "mark-88",
    description: "Unlocked automatically at account level 88.",
  },
  {
    level: 89,
    kind: "title",
    name: "Vaulted",
    value: "Vaulted",
    description: "Unlocked automatically at account level 89.",
  },
  {
    level: 90,
    kind: "accent",
    name: "Rose Circuit",
    value: "#ff77c8",
    description: "Unlocked automatically at account level 90.",
  },
  {
    level: 91,
    kind: "frame",
    name: "Forge Frame 91",
    value: "frame-4",
    description: "Unlocked automatically at account level 91.",
  },
  {
    level: 92,
    kind: "badge",
    name: "Level 92 Mark",
    value: "mark-92",
    description: "Unlocked automatically at account level 92.",
  },
  {
    level: 93,
    kind: "title",
    name: "Daily Five",
    value: "Daily Five",
    description: "Unlocked automatically at account level 93.",
  },
  {
    level: 94,
    kind: "accent",
    name: "Arctic White",
    value: "#e9eef8",
    description: "Unlocked automatically at account level 94.",
  },
  {
    level: 95,
    kind: "frame",
    name: "Forge Frame 95",
    value: "frame-8",
    description: "Unlocked automatically at account level 95.",
  },
  {
    level: 96,
    kind: "badge",
    name: "Level 96 Mark",
    value: "mark-96",
    description: "Unlocked automatically at account level 96.",
  },
  {
    level: 97,
    kind: "title",
    name: "Rookie",
    value: "Rookie",
    description: "Unlocked automatically at account level 97.",
  },
  {
    level: 98,
    kind: "accent",
    name: "Violet Core",
    value: "#875cff",
    description: "Unlocked automatically at account level 98.",
  },
  {
    level: 99,
    kind: "frame",
    name: "Forge Frame 99",
    value: "frame-4",
    description: "Unlocked automatically at account level 99.",
  },
  {
    level: 100,
    kind: "badge",
    name: "Level 100 Mark",
    value: "mark-100",
    description: "Unlocked automatically at account level 100.",
  },
];
